### ISSUE TITLE
Issue with custom STATICI18N_PACKAGES in 1.8.0 (Django 2.0.6, py 3.6.5)

### ISSUE THREAD

**Issue by classifaddict** [zyegfryed/django-statici18n#42]
Hi,

For example, if I set STATICI18N_PACKAGES = ('webui',)

Then:
> python manage.py compilejsi18n --locale en                        
processing language en
Traceback (most recent call last):
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/ipcpubprep/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/statici18n/management/commands/compilejsi18n.py", line 126, in handle
    self._create_output(outputdir, outputformat, locale, domain, packages)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/statici18n/management/commands/compilejsi18n.py", line 91, in _create_output
    data = self._create_javascript_catalog(locale, domain, packages)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/statici18n/management/commands/compilejsi18n.py", line 62, in _create_javascript_catalog
    response = catalog.get(self, None, domain=domain, packages=packages)
  File "/home/collioud/Workspace/IPC_Pub_Prep_V7py3/venv/lib/python3.6/site-packages/django/views/i18n.py", line 226, in get
    packages = packages.split('+') if packages else self.packages
AttributeError: 'tuple' object has no attribute 'split'

Everything is fine with 1.7.0 if I set STATICI18N_PACKAGES = 'webui'

Thanks.

**Comment by zyegfryed** [comment]
Hi @classifaddict ,
You're right, it's a regression introduced by #39 which implicitly requires `STATICI18N_PACKAGES` to be a string. I'll push a fix in the coming days to handle both list/tuple and string types for this parameter. In the meantime, use a `+`-separated string to specify some packages when generating catalog, e.g. `STATICI18N_PACKAGES = 'webui+mypackage'`.

**Comment by zyegfryed** [comment]
@classifaddict the fix is included in v1.8.1. Thanks for your feedback 🍰
